# Generated by Django 5.0.7 on 2024-12-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartitem_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='customer',
        ),
    ]
