# Generated by Django 5.0.7 on 2025-01-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='email',
        ),
    ]
