# Generated by Django 5.0.7 on 2025-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='email',
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
