# Generated by Django 5.0.7 on 2025-01-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_orderaddress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
