# Generated by Django 5.0.7 on 2025-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderaddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='email',
            field=models.EmailField(default='customer@gmail.com', max_length=254),
        ),
    ]
