# Generated by Django 5.0.7 on 2025-01-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_orderaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='email',
        ),
    ]
